INSERT INTO post (id, title, content, author_id, created_at, like_count, lab_id) VALUES (1, 'What is Lorem Ipsum?', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 1, '2018-11-05 05:41:43.188912', 1, null);
INSERT INTO post (id, title, content, author_id, created_at, like_count, lab_id) VALUES (2, 'Where does it come from?', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
', 2, '2018-11-04 05:46:23.578057', 1, null);
INSERT INTO post (id, title, content, author_id, created_at, like_count, lab_id) VALUES (3, 'A five para long lorem ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper tempus erat vitae molestie. Quisque tristique orci in nisi eleifend tempor. Quisque eleifend mattis rhoncus. Phasellus pretium quam in ipsum vestibulum, ut dictum justo consectetur. Nunc in ex venenatis, imperdiet nisl id, facilisis velit. Etiam consectetur eu nisi venenatis dignissim. Vestibulum aliquet tincidunt euismod. Aliquam vehicula interdum sapien eget gravida. Sed euismod neque enim, sollicitudin rutrum dolor pharetra vitae. Quisque vel velit pellentesque, vestibulum mi sed, auctor turpis.

Pellentesque rhoncus risus quis lorem convallis mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus vel velit in est hendrerit lobortis. Aenean aliquam ex ac ligula viverra mattis. Donec pharetra vulputate eros, vitae pharetra velit faucibus sed. Vivamus nec blandit risus, non pharetra lacus. Quisque turpis dui, posuere nec vestibulum tincidunt, pellentesque quis nisl. Fusce at dui ultricies, suscipit eros non, imperdiet metus. Ut finibus porta molestie.

Maecenas id orci dapibus, placerat massa at, malesuada sapien. Etiam est turpis, faucibus at orci id, finibus congue massa. Vestibulum dictum ullamcorper urna ut consectetur. Integer sit amet massa accumsan nisi elementum rhoncus. Donec fermentum elit eget mi convallis, ac faucibus orci finibus. In purus nunc, vestibulum quis luctus sagittis, convallis a odio. Nullam vehicula nisi faucibus fermentum feugiat. Pellentesque vestibulum blandit tortor, ut sodales libero sollicitudin at. Sed id cursus nulla. Donec ullamcorper erat rhoncus mauris rutrum, eget consectetur nibh rhoncus. Donec ante quam, rhoncus sed pellentesque sit amet, malesuada in libero. Morbi semper vel lorem in scelerisque. Curabitur at elementum elit. Nunc mi purus, tempus sed egestas nec, rhoncus et nibh. Nam quis orci eget mi pretium sagittis. Proin ante diam, sagittis quis nisl eget, dapibus pretium dolor.

Sed eu pellentesque lectus. Ut viverra nisl eget dui efficitur, ac egestas arcu molestie. Suspendisse gravida, est a euismod aliquet, orci nibh imperdiet quam, nec mattis ante massa sit amet nisi. Suspendisse dictum porttitor nunc, ac malesuada sem placerat et. Donec et pulvinar sem, id laoreet lorem. Phasellus sodales metus eu metus congue pulvinar. Integer ullamcorper ac erat laoreet scelerisque.

Phasellus sed libero eu justo ornare laoreet. Quisque non est erat. Aenean ex odio, semper a massa eget, porta dapibus odio. Mauris nec vestibulum libero, nec dignissim odio. Praesent eget nisi tincidunt, congue ex eu, tincidunt risus. Curabitur imperdiet dictum orci nec viverra. Curabitur faucibus nulla nec sodales sollicitudin. Sed non porta erat.', 2, '2018-11-05 05:47:14.052494', 0, null);
INSERT INTO post (id, title, content, author_id, created_at, like_count, lab_id) VALUES (4, 'This is Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 3, '2018-11-05 05:41:43.188912', 0, null);